# Devorce Predictor using Neural Network with Keras

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

## Load dataset

In [2]:
data = pd.read_excel("divorce.xlsx")
data.head()

Atr1  Atr2  Atr3  Atr4  Atr5  Atr6  Atr7  Atr8  Atr9  Atr10  ...  Atr46  \
0     2     2     4     1     0     0     0     0     0      0  ...      2   
1     4     4     4     4     4     0     0     4     4      4  ...      2   
2     2     2     2     2     1     3     2     1     1      2  ...      3   
3     3     2     3     2     3     3     3     3     3      3  ...      2   
4     2     2     1     1     1     1     0     0     0      0  ...      2   

   Atr47  Atr48  Atr49  Atr50  Atr51  Atr52  Atr53  Atr54  Class  
0      1      3      3      3      2      3      2      1      1  
1      2      3      4      4      4      4      2      2      1  
2      2      3      1      1      1      2      2      2      1  
3      2      3      3      3      3      2      2      2      1  
4      1      2      3      2      2      2      1      0      1  

[5 rows x 55 columns]

In [3]:
X = data.drop('Class', axis = 'columns')
y = data.Class

In [4]:
X.head()

Atr1  Atr2  Atr3  Atr4  Atr5  Atr6  Atr7  Atr8  Atr9  Atr10  ...  Atr45  \
0     2     2     4     1     0     0     0     0     0      0  ...      3   
1     4     4     4     4     4     0     0     4     4      4  ...      2   
2     2     2     2     2     1     3     2     1     1      2  ...      2   
3     3     2     3     2     3     3     3     3     3      3  ...      3   
4     2     2     1     1     1     1     0     0     0      0  ...      2   

   Atr46  Atr47  Atr48  Atr49  Atr50  Atr51  Atr52  Atr53  Atr54  
0      2      1      3      3      3      2      3      2      1  
1      2      2      3      4      4      4      4      2      2  
2      3      2      3      1      1      1      2      2      2  
3      2      2      3      3      3      3      2      2      2  
4      2      1      2      3      2      2      2      1      0  

[5 rows x 54 columns]

In [5]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: Class, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state=0)

## data preprocessing

In [7]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
X_train

array([[ 0.70288131,  0.22669586,  0.80794664, ...,  0.97787565,
         1.21863233,  1.19167434],
       [ 0.101134  ,  0.22669586,  0.80794664, ...,  0.97787565,
         1.21863233,  1.19167434],
       [ 0.70288131,  1.54263767,  1.48983069, ...,  0.97787565,
         0.53458871,  1.19167434],
       ...,
       [ 1.30462862,  0.22669586,  0.1260626 , ...,  0.97787565,
         0.53458871,  1.19167434],
       [-1.10236062, -1.08924595, -1.2377055 , ...,  0.28931232,
         0.53458871, -0.04683436],
       [ 0.70288131,  0.88466676,  0.1260626 , ...,  0.97787565,
         1.21863233,  1.19167434]])

## import various keras libraries

In [9]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout 

Using TensorFlow backend.
C:\Users\hp\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\hp\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\hp\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\hp\anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarn

## model Building

In [10]:
model = Sequential()

In [11]:
# adding first hidden layer with input layer
model.add(Dense(units=170, activation='relu', input_dim=54))
# adding second hidden layer
model.add(Dense(units=170, activation='relu'))
# adding second hidden layer
model.add(Dense(units=100, activation='relu'))

# adding output layer
model.add(Dense(units=1, activation='sigmoid'))

In [12]:
# compile the model with optimizer and loss
model.compile(optimizer='adamax', loss = 'binary_crossentropy', metrics=['accuracy'])

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


In [13]:
# train the model with neural net
model.fit(X_train, y_train, batch_size=10, epochs=100, validation_split=0.33)


Train on 79 samples, validate on 40 samples
Epoch 1/100
79/79 [==============================] - 0s 5ms/step - loss: 0.2724 - accuracy: 0.9114 - val_loss: 0.0807 - val_accuracy: 0.9750
Epoch 2/100
79/79 [==============================] - 0s 620us/step - loss: 0.0432 - accuracy: 0.9873 - val_loss: 0.0712 - val_accuracy: 0.9750
Epoch 3/100
79/79 [==============================] - 0s 575us/step - loss: 0.0346 - accuracy: 0.9873 - val_loss: 0.0753 - val_accuracy: 0.9750
Epoch 4/100
79/79 [==============================] - 0s 552us/step - loss: 0.0299 - accuracy: 0.9873 - val_loss: 0.0750 - val_accuracy: 0.9750
Epoch 5/100
79/79 [==============================] - 0s 532us/step - loss: 0.0242 - accuracy: 0.9873 - val_loss: 0.0738 - val_accuracy: 0.9750
Epoch 6/100
79/79 [==============================] - 0s 432us/step - loss: 0.0206 - accuracy: 0.9873 - val_loss: 0.0720 - val_accuracy: 0.9750
Epoch 7/100
79/79 [==============================] - 0s 469us/step - loss: 0.0164 - accuracy: 0.987

79/79 [==============================] - 0s 354us/step - loss: 1.1319e-04 - accuracy: 1.0000 - val_loss: 0.1203 - val_accuracy: 0.9750
Epoch 56/100
79/79 [==============================] - 0s 466us/step - loss: 1.0960e-04 - accuracy: 1.0000 - val_loss: 0.1207 - val_accuracy: 0.9750
Epoch 57/100
79/79 [==============================] - 0s 440us/step - loss: 1.0555e-04 - accuracy: 1.0000 - val_loss: 0.1211 - val_accuracy: 0.9750
Epoch 58/100
79/79 [==============================] - 0s 356us/step - loss: 1.0045e-04 - accuracy: 1.0000 - val_loss: 0.1215 - val_accuracy: 0.9750
Epoch 59/100
79/79 [==============================] - 0s 395us/step - loss: 9.5795e-05 - accuracy: 1.0000 - val_loss: 0.1219 - val_accuracy: 0.9750
Epoch 60/100
79/79 [==============================] - 0s 693us/step - loss: 9.2271e-05 - accuracy: 1.0000 - val_loss: 0.1223 - val_accuracy: 0.9750
Epoch 61/100
79/79 [==============================] - 0s 603us/step - loss: 8.8002e-05 - accuracy: 1.0000 - val_loss: 0.1227 

In [14]:
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score
score = accuracy_score(y_pred, y_test)

In [15]:
cm

array([[27,  0],
       [ 2, 22]], dtype=int64)

In [16]:
score

0.9607843137254902

In [17]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 170)               9350      
_________________________________________________________________
dense_2 (Dense)              (None, 170)               29070     
_________________________________________________________________
dense_3 (Dense)              (None, 100)               17100     
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 101       
Total params: 55,621
Trainable params: 55,621
Non-trainable params: 0
_________________________________________________________________


# Divorce Predictor using Random Forest

In [18]:
from sklearn.ensemble import RandomForestClassifier
RF = RandomForestClassifier()

In [19]:
RF.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [20]:
predict = RF.predict(X_test)

In [21]:
from sklearn.metrics import confusion_matrix
c_matrix = confusion_matrix(predict, y_test)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_pred, y_test)

In [22]:
c_matrix

array([[27,  2],
       [ 0, 22]], dtype=int64)

In [23]:
accuracy

0.9607843137254902